version: "3.2"

services:
  server:
    build:
      context: ./server
      # The base is regarding to the context location (the line above)
      dockerfile: ../docker/server/Dockerfile
    volumes:
      - ./server:/app
    command: wait-for-it express_graphsql_demo_db:3306 -- npm start
    env_file:
      - .env
    ports:
      - 4000:4000
    links:
      - db
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - express_graphSQL_demo_volumes:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 4201:8080

volumes:
  express_graphSQL_demo_volumes:
