version: "3.2"

services:
  server:
    build:
      context: ./server
      # The base is regarding to the context location (the line above)
      dockerfile: ../docker/server/Dockerfile
    volumes:
      - ./server:/app
    command: npm start
    env_file:
      - ./server/.env
    ports:
      - 3000:3000
    